services:
  ssh:
    image: lscr.io/linuxserver/openssh-server:latest
    environment:
      - PASSWORD_ACCESS=true
      - USER_NAME=test_user
      - USER_PASSWORD=test_password
      - LOG_STDOUT=true
    ports:
      - "2222:2222"
    volumes:
      - ./test/config:/config
      - ./test/creds/ca.pub:/etc/ssh/ca.pub
